module.exports=function(grunt){
  grunt.initConfig({
    less:{
      development:{
        files:{
          'css/layout.css':'less/layout.less'
        }
      }
    }
  });
  grunt.loadNpTasks('grunt-contrib-less');
  grunt.registerTask('default',['less']);
}
